server:
    env: dev
    host: "0.0.0.0"
    port: "80"
    apipath: "/nearby
database:
    database: "videodatabase"
    user: "postgres"
    password: "padma1675"
    host: "127.0.0.1"
    port: "5432"